In [8]:
import numpy as np
from sklearn.datasets import make_classification

In [ ]:
class Perceptron:
    def __init__(self, n_neurons=1):
        self.n_neurons = n_neurons

    def activation_func(self, z):
        return 0 if z < 0.5 else 1

    def loss(self, prediction, y):
        return y - prediction

    def train(self, X, y):
        predict = self.predict(X)
        error = self.loss(predict, y)

        for i in range(self.n_neurons):
            self.w[1:, i] += (self.learning_rate * error[:, i].dot(X)).reshape((self.n_features,))
            self.w[0, i] += self.learning_rate * np.sum(error[:, i]) / self.n_features

    def vote_funct(self, predictions):
        vote_prediction = []
        i = 0
        for index in np.argmax(predictions, axis=1):
            vote_prediction.append(predictions[i][index])
            i += 1
        return np.array(vote_prediction)
    
    def predict(self, X):
        Z = X.dot(self.w[1:]) + self.w[0]
        predictions = np.array([[self.activation_func(z) for z in row] for row in Z])
        return self.vote_funct(predictions)


    def fit(self, X, y, epochs=1000, learning_rate=0.1):
        self.n_features = X.shape[1]
        self.w = np.random.rand(self.n_features + 1, self.n_neurons)
        self.learning_rate = learning_rate

        if len(y.shape) == 1:
            y = y.reshape(-1, 1)
        for e in range(epochs):
            self.train(X, y)
        return self

In [24]:
X, y = make_classification(n_classes=2, n_clusters_per_class=1)

model = Perceptron(n_neurons=3).fit(X, y, epochs=1000, learning_rate=0.1)

predictions = model.predict(X)
print("Accuracy:", np.sum(predictions == y) / X.shape[0])

[[1 1 0]
 [0 0 0]
 [0 1 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]
 [1 0 1]
 [0 1 0]
 [1 1 1]
 [0 1 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]
 [1 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [1 1 1]
 [0 0 0]
 [1 1 0]
 [0 0 0]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 1]
 [1 0 1]
 [1 0 1]
 [1 1 1]
 [0 1 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]]
[[0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
